@hostname=http://localhost:3000
@prodname=https://jtroffweek02l03.onrender.com

get {{hostname}}/contacts

###

get {{hostname}}/contacts/6448a2f521bf3ddd97025498

###

post {{hostname}} /contacts
Content-Type: application/json

{
    "firstName": "Jeremy", 
    "lastName": "Troff", 
    "email": "jtroff77@gmail.com", 
    "favoriteColor": "Blue", 
    "birthday": "11/19/1992"
}

###

put {{hostname}}/contacts/6448a2f521bf3ddd97025498
Content-Type: application/json

{
    "firstName": "Jeremy", 
    "lastName": "Troff", 
    "email": "jtroff77@gmail.com", 
    "favoriteColor": "Black", 
    "birthday": "11/19/1992"
}

###

delete {{hostname}}/contacts/6448a2f521bf3ddd97025498

###

get {{prodname}}/contacts

###

get {{prodname}}/contacts/644d9a03575d076bff7ef726

###

post {{prodname}} /contacts
Content-Type: application/json

{
    "firstName": "Jeremy", 
    "lastName": "Troff", 
    "email": "jtroff77@gmail.com", 
    "favoriteColor": "Blue", 
    "birthday": "11/19/1992"
}

###

put {{prodname}}/contacts/644d9a03575d076bff7ef726
Content-Type: application/json

{
    "firstName": "Jeremy", 
    "lastName": "Troff", 
    "email": "jtroff77@gmail.com", 
    "favoriteColor": "Black", 
    "birthday": "11/19/1992"
}

###

delete {{prodname}}/contacts/6449f08abcf00d10c195aa97