@hostname=http://localhost:3000
@prodname=https://jtroffpersonalProject.onrender.com

get {{hostname}}/games

###

get {{hostname}}/games/6453307a0b939d53b49b5722

###

post {{hostname}}/games
Content-Type: application/json

{
    "gameName": "Telestration",
    "creator": "Unknown",
    "gameType": "Board Game",
    "gameGenre": "Party",
    "numberPlayers": "4-8",
    "playTime": "30 Min",
    "difficultyToLearn": "Easy",
    "recommended": "7/10"
}

###

put {{hostname}}/games/6453307a0b939d53b49b5722
Content-Type: application/json

{
    "gameName": "Telestrations",
    "creator": "Unknown",
    "gameType": "Board Game",
    "gameGenre": "Party",
    "numberPlayers": "4-8",
    "playTime": "30 Min",
    "difficultyToLearn": "Easy",
    "recommended": "7/10"
}

###

delete {{hostname}}/games/6453307a0b939d53b49b5722

###

get {{hostname}}/players

###

get {{hostname}}/players/6453307a0b939d53b49b5722

###

post {{hostname}}/players
Content-Type: application/json

{
    "firstName": "Caitlyn",
    "lastName": "Rubow",
    "phone": "NA",
    "email": "caitRubow77@gmail.com",
    "favoriteGenre": "Party"
}

###

put {{hostname}}/players/6453307a0b939d53b49b5722
Content-Type: application/json

{
    "firstName": "Cait",
    "lastName": "Rubow",
    "phone": "NA",
    "email": "caitRubow77@gmail.com",
    "favoriteGenre": "Party"
}

###

delete {{hostname}}/players/6453307a0b939d53b49b5722

###

get {{prodname}}/games

###

get {{prodname}}/games/644d9a03575d076bff7ef726

###

post {{prodname}}/games
Content-Type: application/json

{
    "gameName": "Telestration",
    "creator": "Unknown",
    "gameType": "Board Game",
    "gameGenre": "Party",
    "numberPlayers": "4-8",
    "playTime": "30 Min",
    "difficultyToLearn": "Easy",
    "recommended": "7/10"
}

###

put {{prodname}}/games/6453307a0b939d53b49b5722
Content-Type: application/json

{
    "gameName": "Telestrations",
    "creator": "Unknown",
    "gameType": "Board Game",
    "gameGenre": "Party",
    "numberPlayers": "4-8",
    "playTime": "30 Min",
    "difficultyToLearn": "Easy",
    "recommended": "7/10"
}

###

delete {{prodname}}/games/6453307a0b939d53b49b5722

###

get {{prodname}}/players

###

get {{prodname}}/players/644d9a03575d076bff7ef726

###

post {{prodname}}/players
Content-Type: application/json

{
    "firstName": "Caitlyn",
    "lastName": "Rubow",
    "phone": "NA",
    "email": "caitRubow77@gmail.com",
    "favoriteGenre": "Party"
}

###

put {{prodname}}/players/6453307a0b939d53b49b5722
Content-Type: application/json

{
    "firstName": "Cait",
    "lastName": "Rubow",
    "phone": "NA",
    "email": "caitRubow77@gmail.com",
    "favoriteGenre": "Party"
}

###

delete {{prodname}}/players/6453307a0b939d53b49b5722